spring.application.name=zipmap

<<<<<<< HEAD
# Thymeleaf Cache Disable
spring.thymeleaf.cache=false

# MySQL Setting
spring.datasource.url=jdbc:mysql://localhost:3306/zipmap
spring.datasource.username=root
spring.datasource.password=0000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis Setting
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.daedong.zipmap.domain

# -------------------------------------------------
# File Upload Configuration
# -------------------------------------------------
# 1. Custom property for upload directory path
file.upload-dir=C:/upload/

# 2. Standard Spring Boot properties for multipart file uploads
# Maximum size of a single file
spring.servlet.multipart.max-file-size=10MB
# Maximum size of a request (including all files and form data)
spring.servlet.multipart.max-request-size=10MB
=======
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/zipmap?serverTimezone=Asia/Seoul
spring.profiles.include=secret

mybatis.mapper-locations=mappers/*Mapper.xml
mybatis.configuration.map-underscore-to-camel-case=true

# SQL Logging
logging.level.com.example.board.repository=TRACE

# DevTools
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

# File upload directiroy
file.upload-dir = D:/SaDang/IntelliJ/workspace/board/files
>>>>>>> a7cc26fb9e39c7795fcb28ebf805ca96108a4079
